// Snaps hand-picked waypoints to real roads with the OSRM demo server and writes ops/src/roads.ts.
// Run once when routes change; the result is committed so simulations never need the network.
import { writeFileSync } from "node:fs";

const loops = {
  // Downtown streets.
  city: [[43.6426, -79.3871], [43.6489, -79.3815], [43.6532, -79.3832], [43.6629, -79.3957], [43.6677, -79.3948], [43.6702, -79.386], [43.662, -79.376], [43.6561, -79.3802], [43.648, -79.379]],
  // Gardiner and the Don Valley Parkway.
  highway: [[43.6355, -79.42], [43.639, -79.37], [43.6555, -79.355], [43.7, -79.34], [43.75, -79.33], [43.7, -79.342], [43.6555, -79.356], [43.639, -79.371]],
  // Two short downtown loops for the two simulator phones.
  loopA: [[43.6532, -79.3832], [43.658, -79.3832], [43.658, -79.377], [43.6532, -79.377]],
  loopB: [[43.65, -79.387], [43.65, -79.396], [43.656, -79.396], [43.656, -79.387]],
};

const out = {};
for (const [name, points] of Object.entries(loops)) {
  const coords = [...points, points[0]].map(([lat, lng]) => `${lng},${lat}`).join(";");
  const res = await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&continue_straight=true`);
  const json = await res.json();
  if (json.code !== "Ok") throw new Error(`${name}: ${json.code}`);
  out[name] = json.routes[0].geometry.coordinates.map(([lng, lat]) => ({ lat: Math.round(lat * 1e5) / 1e5, lng: Math.round(lng * 1e5) / 1e5 }));
  console.log(name, out[name].length, "points", Math.round(json.routes[0].distance), "m");
  await new Promise((r) => setTimeout(r, 1200));
}

const body = Object.entries(out)
  .map(([name, pts]) => `  ${name}: [\n${pts.map((p) => `    { lat: ${p.lat}, lng: ${p.lng} },`).join("\n")}\n  ],`)
  .join("\n");
writeFileSync(new URL("../ops/src/roads.ts", import.meta.url), `// Generated by scripts/make-routes.mjs from OpenStreetMap roads via OSRM. Do not edit by hand.\nexport const ROADS = {\n${body}\n} as const;\n`);
