// Snaps hand-picked waypoints to real roads with the OSRM demo server and writes ops/src/roads.ts.
// Run once when routes change; the result is committed so simulations never need the network.
import { writeFileSync } from "node:fs";

const loops = {
  // Downtown streets.
  city: [[43.6426, -79.3871], [43.6489, -79.3815], [43.6532, -79.3832], [43.6629, -79.3957], [43.6677, -79.3948], [43.6702, -79.386], [43.662, -79.376], [43.6561, -79.3802], [43.648, -79.379]],
  // Gardiner and the Don Valley Parkway.
  highway: [[43.6355, -79.42], [43.639, -79.37], [43.6555, -79.355], [43.7, -79.34], [43.75, -79.33], [43.7, -79.342], [43.6555, -79.356], [43.639, -79.371]],
  // Two short downtown loops for the two simulator phones.
  loopA: [[43.6532, -79.3832], [43.658, -79.3832], [43.658, -79.377], [43.6532, -79.377]],
  loopB: [[43.65, -79.387], [43.65, -79.396], [43.656, -79.396], [43.656, -79.387]],
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const osrm = async (coords, extra = "") => {
  const url = `https://router.project-osrm.org/route/v1/driving/${coords.map(([lat, lng]) => `${lng},${lat}`).join(";")}?overview=full&geometries=geojson&continue_straight=true${extra}`;
  const json = await (await fetch(url)).json();
  if (json.code !== "Ok") throw new Error(json.code);
  await sleep(1200);
  return json;
};

// Waypoints that are not on a road make the router add a spur out to the road and back. Snap them first, then route
// through the snapped points, then trim any remaining out-and-back so a car only ever drives forward.
const bearing = (a, b) => (Math.atan2((b.lng - a.lng) * Math.cos((a.lat * Math.PI) / 180), b.lat - a.lat) * 180) / Math.PI;
const reverses = (a, b, c) => {
  const d = Math.abs(((bearing(a, b) - bearing(b, c) + 540) % 360) - 180);
  return d > 150;
};
function trimSpurs(pts) {
  let changed = true;
  while (changed) {
    changed = false;
    for (let i = 1; i < pts.length - 1; i++) {
      if (reverses(pts[i - 1], pts[i], pts[i + 1])) {
        // Drop the tip of the spur and the point after it that doubles back.
        pts.splice(i, 2);
        changed = true;
        break;
      }
    }
  }
  return pts;
}

const out = {};
for (const [name, points] of Object.entries(loops)) {
  const closed = [...points, points[0]];
  const first = await osrm(closed);
  const snapped = first.waypoints.map((w) => [w.location[1], w.location[0]]);
  const second = await osrm(snapped);
  const raw = second.routes[0].geometry.coordinates.map(([lng, lat]) => ({ lat: Math.round(lat * 1e5) / 1e5, lng: Math.round(lng * 1e5) / 1e5 }));
  // Remove duplicate neighbours, then spurs.
  const dedup = raw.filter((p, i) => i === 0 || p.lat !== raw[i - 1].lat || p.lng !== raw[i - 1].lng);
  out[name] = trimSpurs(dedup);
  console.log(name, raw.length, "->", out[name].length, "points", Math.round(second.routes[0].distance), "m");
}

const body = Object.entries(out)
  .map(([name, pts]) => `  ${name}: [\n${pts.map((p) => `    { lat: ${p.lat}, lng: ${p.lng} },`).join("\n")}\n  ],`)
  .join("\n");
writeFileSync(new URL("../ops/src/roads.ts", import.meta.url), `// Generated by scripts/make-routes.mjs from OpenStreetMap roads via OSRM. Do not edit by hand.\nexport const ROADS = {\n${body}\n} as const;\n`);
